version: '3.9'

services:
  web:
      build:
        context: .
        dockerfile: ./backend/Dockerfile
      container_name: fastapi-web
      command: /bin/bash -c "cd backend && alembic upgrade head && uvicorn --app-dir /app/backend/src main:app --host 0.0.0.0 --port 8000"
      ports:
        - "8000:8000"
      env_file:
        - .env
      environment:
        PYTHONPATH: /app/backend
      depends_on:
        - db
        - minio
      volumes:
        - ./backend:/app/backend
        - ./backend/runs/detect/plant_disease_exp3:/app/model
        - ./ai_model:/app/ai_model
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "3000:80"
    depends_on:
      - web

  
    


  db:
    image: postgres:14
    container_name: cv-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: cv-minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    env_file: .env
    volumes:
      - minio_data:/data
      - ./init-minio.sh:/usr/bin/init-minio.sh
    entrypoint: /usr/bin/init-minio.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo '...waiting for minio...'
        sleep 1
      done;
      mc mb myminio/plant-disease-image || true;
      mc anonymous set public myminio/plant-disease-image;
      
      echo 'MinIO buckets created and configured';
      exit 0;
      "
volumes:
  postgres_data:
  minio_data: